const TheorySlotOptions = [
  { label: "A", value: "A1" },
  { label: "B", value: "B1" },
  { label: "C", value: "C1" },
  { label: "D", value: "D1" },
  { label: "E", value: "E1" },
  { label: "F", value: "F1" },
  { label: "G", value: "G1" },

  // TAx type slots
  { label: "A + TA", value: "A1 + TA1" },
  { label: "B + TB", value: "B1 + TB1" },
  { label: "C + TC", value: "C1 + TC1" },
  { label: "D + TD", value: "D1 + TD1" },
  { label: "E + TE", value: "E1 + TE1" },
  { label: "F + TF", value: "F1 + TF1" },
  { label: "G + TG", value: "G1 + TG1" },

  // TAAx type slots
  { label: "A + TA + TAA", value: "A1 + TA1 + TAA1" },
  { label: "B + TB + TBB", value: "B1 + TB1 + TBB1" },
  { label: "C + TC + TCC", value: "C1 + TC1 + TCC1" },
  { label: "D + TD + TDD", value: "D1 + TD1 + TDD1" },

];


const LabSlotOptions = [
  { value: "L1", label: "L1" },
  { value: "L2", label: "L2" },
  { value: "L3", label: "L3" },
  { value: "L4", label: "L4" },
  { value: "L5", label: "L5" },
  { value: "L6", label: "L6" },
  { value: "L7", label: "L7" },
  { value: "L8", label: "L8" },
  { value: "L9", label: "L9" },
  { value: "L10", label: "L10" },
  { value: "L11", label: "L11" },
  { value: "L12", label: "L12" },
  { value: "L13", label: "L13" },
  { value: "L14", label: "L14" },
  { value: "L15", label: "L15" },
  { value: "L16", label: "L16" },
  { value: "L17", label: "L17" },
  { value: "L18", label: "L18" },
  { value: "L19", label: "L19" },
  { value: "L20", label: "L20" },
  { value: "L21", label: "L21" },
  { value: "L22", label: "L22" },
  { value: "L23", label: "L23" },
  { value: "L24", label: "L24" },
  { value: "L25", label: "L25" },
  { value: "L26", label: "L26" },
  { value: "L27", label: "L27" },
  { value: "L28", label: "L28" },
  { value: "L29", label: "L29" },
  { value: "L30", label: "L30" },
  { value: "L31", label: "L31" },
  { value: "L32", label: "L32" },
  { value: "L33", label: "L33" },
  { value: "L34", label: "L34" },
  { value: "L35", label: "L35" },
  { value: "L36", label: "L36" },
  { value: "L37", label: "L37" },
  { value: "L38", label: "L38" },
  { value: "L39", label: "L39" },
  { value: "L40", label: "L40" },
  { value: "L41", label: "L41" },
  { value: "L42", label: "L42" },
  { value: "L43", label: "L43" },
  { value: "L44", label: "L44" },
  { value: "L45", label: "L45" },
  { value: "L46", label: "L46" },
  { value: "L47", label: "L47" },
  { value: "L48", label: "L48" },
  { value: "L49", label: "L49" },
  { value: "L50", label: "L50" },
  { value: "L51", label: "L51" },
  { value: "L52", label: "L52" },
  { value: "L53", label: "L53" },
  { value: "L54", label: "L54" },
  { value: "L55", label: "L55" },
  { value: "L56", label: "L56" },
  { value: "L57", label: "L57" },
  { value: "L58", label: "L58" },
  { value: "L59", label: "L59" },
  { value: "L60", label: "L60" },
];

export { TheorySlotOptions, LabSlotOptions }
